### ISSUE TITLE
Highlight the latest

### ISSUE THREAD

**Issue by e-minguez** [ctron/openshift-update-graph#1]
This is super cool and super useful, thanks!

I think it would be nice to highlight the latest one (maybe making it 'preselected' when you choose the channel?) as well as adding links to download the cli tools, etc. (such as I did here https://versions.openshift.tips/ so I can deprecate it :D)

Thanks!

**Comment by ctron** [comment]
Indeed, that sounds like a great idea … PRs are welcome :grin: … but I will definitely take a look at this, when I find some time.

**Comment by e-minguez** [comment]
@mvazquezc forked your repo and added the highlight + download links as well as the ability to select a different endpoint, see https://github.com/mvazquezc/openshift-update-graph-viewer
It is currently being hosted in https://graph.openshift.tips

**Comment by ctron** [comment]
That looks great. I am only not so fond of the "api endpoint" form in the header. I do understand the reason for it.

I am not sure I would really expose this to a user in that way. Would it be sufficient to provide this using an additional query parameter? IIRC it should be possible to retrieve that in the frontend code as well.

**Comment by ctron** [comment]
I add the feature to mark the most recent version in a channel. And I also ported over the download links box.
