### ISSUE TITLE
Latest is not 'connected'

### ISSUE THREAD

**Issue by gmcbrien** [ctron/openshift-update-graph#2]
Awesome tool, thanks a lot!
Currently, 4.6.9 (latest version) does not show any update paths. It is floating on its own (see screeshot). Is this by design...?
Thanks a lot

![12121](https://user-images.githubusercontent.com/31663967/104599039-95d82700-5677-11eb-9c56-19d550196c9b.jpg)

**Comment by sdodson** [comment]
I'm not the author on this repo but someone who maintains the graph itself. Yes, that's an accurate reflection of the state of the graph right now.

Maybe it'd be interesting if latest points at the latest version with incoming edges?

**Comment by ctron** [comment]
Hm an interesting case indeed …

I guess it really is the latest … just not the latest you are expecting :grimacing: … You (and me) are interested in the "latest upgradeable".

> Maybe it'd be interesting if latest points at the latest version with incoming edges?

That might be a good compromise. There would still be the case of 4.6.9 being disconnected, but having an upgrade to 4.6.10 … then that would still become the "most recent", but I guess that is ok.

**Comment by ctron** [comment]
Taking a look at the graph … I guess if we change that behavior someone might complain about "latest" not being "latest" … 

Maybe it would be better to put a note that this can happen. :grin:

**Comment by sdodson** [comment]
Yeah, this is all temporary. I just wanted to point out that the rendering is accurate because we blocked upgrades to 4.6.9. Once we introduce new 4.6.z it will include upgrades from 4.6.9 and it will again be connected. You can see this now in the candidate channel with 4.6.12.

![image](https://user-images.githubusercontent.com/48161/104753256-b9f24180-5725-11eb-916b-57886537b217.png)

**Comment by ctron** [comment]
I think it is a valid issue. However, I can't think of any real improvement here, other than having this documented here. I will close the issue, and leave the current behavior as is.

In any case, thanks for the report and thanks for the explanation. This might help other to understand what is going on.
