### ISSUE TITLE
Add 4.7 channels 

### ISSUE THREAD

**Issue by dmoessne** [ctron/openshift-update-graph#3]
With GA of 4.7 those channels should be added as well, see https://ocp-upgrade.net/47/candidate-47.svg

**Comment by ctron** [comment]
However, there is not much that I can do. The source of this information is here: https://github.com/openshift/cincinnati-graph-data/tree/master/channels

Currently that lists only a "candidate 4.7" channel. As soon as metadata is published, this repository will pick it up (with a bit of delay). You should be able to see the same output as the linked SVG here: https://ctron.github.io/openshift-update-graph/#candidate-4.7

What remains to be done is to set the "default channel" to 4.7. I normally wait for this until an update path on the stable channel is available.

**Comment by ctron** [comment]
Just re-checked: `stable-4.7` was picked up now: https://ctron.github.io/openshift-update-graph/#stable-4.7
